export const URL_BLACKLIST = [
  'action=edit',
  'redlink=1',
  '/Special:',
  '/Template:',
  '/Template_talk:',
  '/User:',
  '/User_talk:',
  '/Wikipedia:',
  '/Wikipedia_talk:',
  '/File:',
  '/File_talk:',
  '/MediaWiki:',
  '/MediaWiki_talk:',
  '/Help:',
  '/Help_talk:',
  '/Category:',
  '/Category_talk:',
  '/Portal:',
  '/Portal_talk:',
  '/Book:',
  '/Book_talk:',
  '/Draft:',
  '/Draft_talk:',
  '/TimedText:',
  '/TimedText_talk:',
  '/Module:',
  '/Module_talk:'
];

export const FETCH_RETRIES = 3;
